Acme\TodoBundle\Entity\Task:
    type: entity
    table: todo_task
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        task:
            type: string
            length: 255
        dueDate:
            type: date
        category:
            type: object
    lifecycleCallbacks: {  }
