acme_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }
acme_store_create_product:
    pattern:  /store/createProduct
    defaults: { _controller: AcmeStoreBundle:Default:createProduct }
acme_store_show_product:
    pattern:  /store/show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }
acme_store_update_product:
    pattern:  /store/update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }
acme_store_delete_product:
    pattern:  /store/delete/{id}
    defaults: { _controller: AcmeStoreBundle:Default:delete }
