parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony_test
    database_user: Thomas
    database_password: e6627
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 30ee9824ec649e8104f5db6686b2c5095
    database_path: null
