parameters:
#    acme_todo.example.class: Acme\TodoBundle\Example

services:
#    acme_todo.example:
#        class: %acme_todo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_todo.form.type.task:
        class: Acme\TodoBundle\Form\Type\TaskType
        tags:
            - { name: form.type, alias: task}