Thomas\Bundle\BookshopBundle\Entity\Book:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        isbn:
            type: string
            length: '13'
    lifecycleCallbacks: {  }
